version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    command: sh -c "cd parkinson-react && npm start"
    ports:
      - "52210:52210"
    stdin_open: true
